/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weatheralarm_android_wealarm_SoundTouch */

#ifndef _Included_com_weatheralarm_android_wealarm_SoundTouch
#define _Included_com_weatheralarm_android_wealarm_SoundTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_getVersionString
  (JNIEnv *, jclass);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    setTempo
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_setTempo
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    setPitchSemiTones
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_setPitchSemiTones
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    setSpeed
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_setSpeed
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    processFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_processFile
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    getErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_getErrorString
  (JNIEnv *, jclass);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_weatheralarm_android_wealarm_SoundTouch
 * Method:    deleteInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_weatheralarm_android_wealarm_SoundTouch_deleteInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
